/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
    id("java")
    id("maven-publish")
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

subprojects {

    apply(plugin = "java-library")
    apply(plugin = "java")
    apply(plugin = "com.github.johnrengelman.shadow")
    apply(plugin = "maven-publish")

    version = property("tne_version")!!

    repositories {
        mavenCentral()
        maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
        maven("https://oss.sonatype.org/content/repositories/snapshots/")
        maven("https://jitpack.io")
        maven("https://plugins.gradle.org/m2/")
        maven("https://repo.codemc.io/repository/maven-public/")
    }

    dependencies {
        compileOnly("net.tnemc:EconomyCore:${project.version}")
    }

    tasks {
        compileJava {
            options.encoding = "UTF-8"

            sourceCompatibility = "17"
            targetCompatibility = "17"
        }

        jar {
            from("../license.md")
        }

        shadowJar {
        }

        processResources {
            filesMatching("**/resources/*") {
                expand(rootProject.project.properties)
            }

            outputs.upToDateWhen { false }
        }
    }
}
