/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java")
    id("com.github.johnrengelman.shadow") version "8.1.1" apply true
}

tasks {
    compileJava {
        sourceCompatibility = "17"
        targetCompatibility = "17"
    }

    jar {
        dependsOn(shadowJar)
        archiveFileName = "original-TNE-Module-${project.version}.jar"
    }

    shadowJar {
        archiveFileName = "TNE-Module-${project.version}.jar"
    }
}

description = "A TNE Module"