/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java")
    id("com.github.johnrengelman.shadow") version "8.1.1" apply true
}

dependencies {
    api(project(":TNE-Module-Core"))
    compileOnly("org.spongepowered:spongeapi:8.2.0-SNAPSHOT")
}

repositories {
    maven("https://repo.spongepowered.org/maven")
}

tasks {
    compileJava {
        sourceCompatibility = "17"
        targetCompatibility = "17"
    }

    jar {
        dependsOn(shadowJar)
        archiveFileName = "original-TNE-Module-Sponge-${project.version}.jar"
    }

    shadowJar {
        archiveFileName = "TNE-Module-Sponge-${project.version}.jar"
    }
}

description = "A TNE Sponge Module"